### ISSUE TITLE
KeyError: 'final_gt'

### ISSUE THREAD

**Issue by agar2995** [val-iisc/crowd-counting-scnn#11]
In data_reader.py", line 72, inside  __iter__, the program throws an error `KeyError: 'final_gt'` for
    `Y = data_mat['final_gt'].astype(theano.config.floatX)`

**Comment by norahik** [comment]
i got the same error , did you manage to solve it ?

**Comment by norahik** [comment]
i tried working with it, so ...
i get that _data_mat_ is a dictionary of the matlab file data 
_final_gt_ is a key in that dictionary, yet in the data set i have there is no key named like so, instead i printed the all the key to find that mine is called _image_info_ 

i'm afraid the structure of the matlab file used here is different than mine, since the file names are also different and i had to fox the code to go around it.

bellow is what i get from printing some information about_data_mat_
i see the structure is complex , i think all we need is the number 1546 (the ground truth) and i don't know how to access it.
now i'm getting an error around Y = data_mat['image_info'].astype(theano.config.floatX)
ValueError: setting an array element with a sequence.

 
`data_mat dict keys: 
['image_info', '__version__', '__header__', '__globals__']
image_info value:
[[array([[(array([[ 29.6225116 , 472.92022152],
       [ 54.35533603, 454.96602305],
       [ 51.79045053, 460.46220626],
       ...,
       [597.89732076, 688.27900015],
       [965.77518336, 638.44693908],
       [166.9965574 , 628.1873971 ]]), array([[1546]], dtype=uint16))]],
      dtype=[('location', 'O'), ('number', 'O')])]]
data_mat dict tuples
[('image_info', array([[array([[(array([[ 29.6225116 , 472.92022152],
       [ 54.35533603, 454.96602305],
       [ 51.79045053, 460.46220626],
       ...,
       [597.89732076, 688.27900015],
       [965.77518336, 638.44693908],
       [166.9965574 , 628.1873971 ]]), array([[1546]], dtype=uint16))]],
      dtype=[('location', 'O'), ('number', 'O')])]], dtype=object)), ('__version__', '1.0'), ('__header__', 'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Nov 18 20:06:05 2016'), ('__globals__', [])]`

**Comment by mtakhsha94** [comment]
@agar2995  
Hi
Do you assess the problem that you've mentioned above?
It's my problem too. :(

**Comment by norahik** [comment]
@mtakhsha94 Make sure you run create dataset first. the key 'final_gt' is the new crowd count key for the segmented ground-truth, you can see this key being used in both create_test_set.m & create_train_set.m in the save function.

**Comment by mtakhsha94** [comment]
@norahik Thanks a lot 👍
